export const generatedPublicConfig = {
  NEXT_PUBLIC_WORKFORCEIQ_API_BASE_URL: "",
  NEXT_PUBLIC_WORKFORCEIQ_ORGANIZATION_ID: "",
  NEXT_PUBLIC_COGNITO_REGION: "",
  NEXT_PUBLIC_COGNITO_USER_POOL_ID: "",
  NEXT_PUBLIC_COGNITO_APP_CLIENT_ID: "",
  NEXT_PUBLIC_COGNITO_DOMAIN: "",
  NEXT_PUBLIC_COGNITO_CALLBACK_URL: "",
  NEXT_PUBLIC_COGNITO_LOGOUT_URL: "",
} as const;
